using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dibk.Ftpb.Validation.Application.Enums
{
    public enum FieldNameEnum
    {
        [FieldNameEnumerationAttribute(FieldNameId = "1")] adresselinje1,
        [FieldNameEnumerationAttribute(FieldNameId = "2")] adresselinje2,
        [FieldNameEnumerationAttribute(FieldNameId = "3")] adresselinje3,
        [FieldNameEnumerationAttribute(FieldNameId = "4")] postnr,
        [FieldNameEnumerationAttribute(FieldNameId = "5")] poststed,
        [FieldNameEnumerationAttribute(FieldNameId = "6")] landkode,
        [FieldNameEnumerationAttribute(FieldNameId = "7")] gatenavn,
        [FieldNameEnumerationAttribute(FieldNameId = "8")] husnr,
        [FieldNameEnumerationAttribute(FieldNameId = "9")] bokstav,
        [FieldNameEnumerationAttribute(FieldNameId = "10")] kommunenummer,
        [FieldNameEnumerationAttribute(FieldNameId = "11")] gaardsnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "12")] bruksnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "13")] festenummer,
        [FieldNameEnumerationAttribute(FieldNameId = "14")] seksjonsnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "15")] bygningsnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "16")] bolignummer,
        [FieldNameEnumerationAttribute(FieldNameId = "17")] kommunenavn,
        [FieldNameEnumerationAttribute(FieldNameId = "18")] foedselsnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "19")] organisasjonsnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "20")] navn,
        [FieldNameEnumerationAttribute(FieldNameId = "21")] telefonnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "22")] mobilnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "23")] epost,
        [FieldNameEnumerationAttribute(FieldNameId = "24")] framtidige,
        [FieldNameEnumerationAttribute(FieldNameId = "25")] faste,
        [FieldNameEnumerationAttribute(FieldNameId = "26")] midlertidige,
        [FieldNameEnumerationAttribute(FieldNameId = "27")] antallAnsatte,
        [FieldNameEnumerationAttribute(FieldNameId = "28")] eksisterende,
        [FieldNameEnumerationAttribute(FieldNameId = "29")] utleieBygg,
        [FieldNameEnumerationAttribute(FieldNameId = "30")] antallVirksomheter,
        [FieldNameEnumerationAttribute(FieldNameId = "31")] beskrivelse,
        [FieldNameEnumerationAttribute(FieldNameId = "32")] bestillerReferanse,
        [FieldNameEnumerationAttribute(FieldNameId = "33")] fakturareferanser,
        [FieldNameEnumerationAttribute(FieldNameId = "34")] prosjektnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "35")] ehfFaktura,
        [FieldNameEnumerationAttribute(FieldNameId = "36")] fakturaPapir,
        [FieldNameEnumerationAttribute(FieldNameId = "37")] signatur,
        [FieldNameEnumerationAttribute(FieldNameId = "38")] kodeverdi,
        [FieldNameEnumerationAttribute(FieldNameId = "39")] kodebeskrivelse,
        [FieldNameEnumerationAttribute(FieldNameId = "40")] nyeEndretAdkomst,
        [FieldNameEnumerationAttribute(FieldNameId = "41")] erTillatelseGittRiksFylkesveg,
        [FieldNameEnumerationAttribute(FieldNameId = "42")] tomtearealByggeomraade,
        [FieldNameEnumerationAttribute(FieldNameId = "43")] tomtearealSomTrekkesFra,
        [FieldNameEnumerationAttribute(FieldNameId = "44")] tomtearealSomLeggesTil,
        [FieldNameEnumerationAttribute(FieldNameId = "45")] tomtearealBeregnet,
        [FieldNameEnumerationAttribute(FieldNameId = "46")] beregnetMaksByggeareal,
        [FieldNameEnumerationAttribute(FieldNameId = "47")] arealBebyggelseEksisterende,
        [FieldNameEnumerationAttribute(FieldNameId = "48")] arealBebyggelseSomSkalRives,
        [FieldNameEnumerationAttribute(FieldNameId = "49")] arealBebyggelseNytt,
        [FieldNameEnumerationAttribute(FieldNameId = "50")] parkeringsarealTerreng,
        [FieldNameEnumerationAttribute(FieldNameId = "51")] arealSumByggesak,
        [FieldNameEnumerationAttribute(FieldNameId = "52")] beregnetGradAvUtnytting,
        [FieldNameEnumerationAttribute(FieldNameId = "53")] beroererTidligere1850,
        [FieldNameEnumerationAttribute(FieldNameId = "54")] forhaandskonferanseAvholdt,
        [FieldNameEnumerationAttribute(FieldNameId = "55")] paalagtUavhengigKontroll,
        [FieldNameEnumerationAttribute(FieldNameId = "56")] beroererArbeidsplasser,
        [FieldNameEnumerationAttribute(FieldNameId = "57")] norskSvenskDansk,
        [FieldNameEnumerationAttribute(FieldNameId = "58")] utarbeideAvfallsplan,
        [FieldNameEnumerationAttribute(FieldNameId = "59")] behovForTillatelse,
        [FieldNameEnumerationAttribute(FieldNameId = "60")] krysserVannforsyningAnnensGrunn,
        [FieldNameEnumerationAttribute(FieldNameId = "61")] tinglystErklaering,
        [FieldNameEnumerationAttribute(FieldNameId = "62")] installereVannklosett,
        [FieldNameEnumerationAttribute(FieldNameId = "63")] utslippstillatelse,
        [FieldNameEnumerationAttribute(FieldNameId = "64")] krysserAvloepAnnensGrunn,
        [FieldNameEnumerationAttribute(FieldNameId = "65")] overvannTerreng,
        [FieldNameEnumerationAttribute(FieldNameId = "66")] overvannAvloepssystem,
        [FieldNameEnumerationAttribute(FieldNameId = "67")] flomutsattOmraade,
        [FieldNameEnumerationAttribute(FieldNameId = "68")] f1,
        [FieldNameEnumerationAttribute(FieldNameId = "69")] f2,
        [FieldNameEnumerationAttribute(FieldNameId = "70")] f3,
        [FieldNameEnumerationAttribute(FieldNameId = "71")] skredutsattOmraade,
        [FieldNameEnumerationAttribute(FieldNameId = "72")] s1,
        [FieldNameEnumerationAttribute(FieldNameId = "73")] s2,
        [FieldNameEnumerationAttribute(FieldNameId = "74")] s3,
        [FieldNameEnumerationAttribute(FieldNameId = "75")] miljoeforhold,
        [FieldNameEnumerationAttribute(FieldNameId = "76")] erLoefteinnretningIBygning,
        [FieldNameEnumerationAttribute(FieldNameId = "77")] planleggesLoefteinnretningIBygning,
        [FieldNameEnumerationAttribute(FieldNameId = "78")] planleggesHeis,
        [FieldNameEnumerationAttribute(FieldNameId = "79")] planleggesTrappeheis,
        [FieldNameEnumerationAttribute(FieldNameId = "80")] planleggesRulletrapp,
        [FieldNameEnumerationAttribute(FieldNameId = "81")] planleggesLoefteplattform,
        [FieldNameEnumerationAttribute(FieldNameId = "82")] konfliktHoeyspentkraftlinje,
        [FieldNameEnumerationAttribute(FieldNameId = "83")] konfliktVannOgAvloep,
        [FieldNameEnumerationAttribute(FieldNameId = "84")] utnyttingsgrad,
        [FieldNameEnumerationAttribute(FieldNameId = "85")] formaal,
        [FieldNameEnumerationAttribute(FieldNameId = "86")] andreRelevanteKrav,
        [FieldNameEnumerationAttribute(FieldNameId = "87")] beskrivPlanlagtFormaal,
        [FieldNameEnumerationAttribute(FieldNameId = "88")] foelgebrev,
        [FieldNameEnumerationAttribute(FieldNameId = "89")] begrunnelse,
        [FieldNameEnumerationAttribute(FieldNameId = "90")] fraSluttbrukersystem,
        [FieldNameEnumerationAttribute(FieldNameId = "91")] ftbId,
        [FieldNameEnumerationAttribute(FieldNameId = "92")] prosjektnavn,
        [FieldNameEnumerationAttribute(FieldNameId = "93")] sluttbrukersystemUrl,
        [FieldNameEnumerationAttribute(FieldNameId = "94")] samtykkeTilByggeplaner,
        [FieldNameEnumerationAttribute(FieldNameId = "95")] klartForSigneringFraSluttbrukersystem,
        [FieldNameEnumerationAttribute(FieldNameId = "96")] fritattFraNabovarsling,
        [FieldNameEnumerationAttribute(FieldNameId = "97")] foreliggerMerknader,
        [FieldNameEnumerationAttribute(FieldNameId = "98")] antallMerknader,
        [FieldNameEnumerationAttribute(FieldNameId = "99")] vurderingAvMerknader,
        [FieldNameEnumerationAttribute(FieldNameId = "100")] soeknadensHjemmeside,
        [FieldNameEnumerationAttribute(FieldNameId = "101")] soeknadSeesKontaktperson,
        [FieldNameEnumerationAttribute(FieldNameId = "102")] harSentralGodkjenning,
        [FieldNameEnumerationAttribute(FieldNameId = "103")] erklaeringAnsvar,
        [FieldNameEnumerationAttribute(FieldNameId = "104")] betaling,
        [FieldNameEnumerationAttribute(FieldNameId = "105")] sjekklistepunktsvar,
        [FieldNameEnumerationAttribute(FieldNameId = "106")] dokumentasjon,
        [FieldNameEnumerationAttribute(FieldNameId = "107")] BRA,
        [FieldNameEnumerationAttribute(FieldNameId = "108")] saksaar,
        [FieldNameEnumerationAttribute(FieldNameId = "109")] sakssekvensnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "110")] hovedinnsendingsnummer,
        [FieldNameEnumerationAttribute(FieldNameId = "116")] erNorskSvenskDansk,
        [FieldNameEnumerationAttribute(FieldNameId = "118")] unntattOffentlighet,
        [FieldNameEnumerationAttribute(FieldNameId = "119")] veiledning,
        [FieldNameEnumerationAttribute(FieldNameId = "120")] type,
        [FieldNameEnumerationAttribute(FieldNameId = "121")] ordreId,
        [FieldNameEnumerationAttribute(FieldNameId = "122")] sum,
        [FieldNameEnumerationAttribute(FieldNameId = "123")] transId,
        [FieldNameEnumerationAttribute(FieldNameId = "124")] gebyrkategori,
        [FieldNameEnumerationAttribute(FieldNameId = "125")] skalFaktureres,

    }
}






