//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace no.kxml.skjema.dibk.ansvarsrettAnsako {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Kode", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class KodeType {
        
        private string kodeverdiField;
        
        private string kodebeskrivelseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kodeverdi {
            get {
                return this.kodeverdiField;
            }
            set {
                this.kodeverdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kodebeskrivelse {
            get {
                return this.kodebeskrivelseField;
            }
            set {
                this.kodebeskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Ansvarsomraade", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class AnsvarsomraadeType {
        
        private string beskrivelseAvAnsvarsomraadeField;
        
        private System.Nullable<bool> dekkesOmraadeAvSentralGodkjenningField;
        
        private bool dekkesOmraadeAvSentralGodkjenningFieldSpecified;
        
        private KodeType funksjonField;
        
        private System.Nullable<bool> samsvarKontrollVedFerdigattestField;
        
        private bool samsvarKontrollVedFerdigattestFieldSpecified;
        
        private System.Nullable<bool> samsvarKontrollVedIgangsettingstillatelseField;
        
        private bool samsvarKontrollVedIgangsettingstillatelseFieldSpecified;
        
        private System.Nullable<bool> samsvarKontrollVedMidlertidigBrukstillatelseField;
        
        private bool samsvarKontrollVedMidlertidigBrukstillatelseFieldSpecified;
        
        private System.Nullable<bool> samsvarKontrollVedRammetillatelseField;
        
        private bool samsvarKontrollVedRammetillatelseFieldSpecified;
        
        private KodeType tiltaksklasseField;
        
        private string soeknadssystemetsReferanseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelseAvAnsvarsomraade {
            get {
                return this.beskrivelseAvAnsvarsomraadeField;
            }
            set {
                this.beskrivelseAvAnsvarsomraadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> dekkesOmraadeAvSentralGodkjenning {
            get {
                return this.dekkesOmraadeAvSentralGodkjenningField;
            }
            set {
                this.dekkesOmraadeAvSentralGodkjenningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dekkesOmraadeAvSentralGodkjenningSpecified {
            get {
                return this.dekkesOmraadeAvSentralGodkjenningFieldSpecified;
            }
            set {
                this.dekkesOmraadeAvSentralGodkjenningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType funksjon {
            get {
                return this.funksjonField;
            }
            set {
                this.funksjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> samsvarKontrollVedFerdigattest {
            get {
                return this.samsvarKontrollVedFerdigattestField;
            }
            set {
                this.samsvarKontrollVedFerdigattestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool samsvarKontrollVedFerdigattestSpecified {
            get {
                return this.samsvarKontrollVedFerdigattestFieldSpecified;
            }
            set {
                this.samsvarKontrollVedFerdigattestFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> samsvarKontrollVedIgangsettingstillatelse {
            get {
                return this.samsvarKontrollVedIgangsettingstillatelseField;
            }
            set {
                this.samsvarKontrollVedIgangsettingstillatelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool samsvarKontrollVedIgangsettingstillatelseSpecified {
            get {
                return this.samsvarKontrollVedIgangsettingstillatelseFieldSpecified;
            }
            set {
                this.samsvarKontrollVedIgangsettingstillatelseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> samsvarKontrollVedMidlertidigBrukstillatelse {
            get {
                return this.samsvarKontrollVedMidlertidigBrukstillatelseField;
            }
            set {
                this.samsvarKontrollVedMidlertidigBrukstillatelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool samsvarKontrollVedMidlertidigBrukstillatelseSpecified {
            get {
                return this.samsvarKontrollVedMidlertidigBrukstillatelseFieldSpecified;
            }
            set {
                this.samsvarKontrollVedMidlertidigBrukstillatelseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> samsvarKontrollVedRammetillatelse {
            get {
                return this.samsvarKontrollVedRammetillatelseField;
            }
            set {
                this.samsvarKontrollVedRammetillatelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool samsvarKontrollVedRammetillatelseSpecified {
            get {
                return this.samsvarKontrollVedRammetillatelseFieldSpecified;
            }
            set {
                this.samsvarKontrollVedRammetillatelseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType tiltaksklasse {
            get {
                return this.tiltaksklasseField;
            }
            set {
                this.tiltaksklasseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string soeknadssystemetsReferanse {
            get {
                return this.soeknadssystemetsReferanseField;
            }
            set {
                this.soeknadssystemetsReferanseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Ansvarsrett", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class AnsvarsrettType {
        
        private ForetakType foretakField;
        
        private AnsvarsomraadeType[] ansvarsomraaderField;
        
        private System.Nullable<bool> erklaeringAnsvarligProsjekterendeField;
        
        private bool erklaeringAnsvarligProsjekterendeFieldSpecified;
        
        private System.Nullable<bool> erklaeringAnsvarligUtfoerendeField;
        
        private bool erklaeringAnsvarligUtfoerendeFieldSpecified;
        
        private System.Nullable<bool> erklaeringAnsvarligKontrollerendeField;
        
        private bool erklaeringAnsvarligKontrollerendeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ForetakType foretak {
            get {
                return this.foretakField;
            }
            set {
                this.foretakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ansvarsomraade", IsNullable=false)]
        public AnsvarsomraadeType[] ansvarsomraader {
            get {
                return this.ansvarsomraaderField;
            }
            set {
                this.ansvarsomraaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> erklaeringAnsvarligProsjekterende {
            get {
                return this.erklaeringAnsvarligProsjekterendeField;
            }
            set {
                this.erklaeringAnsvarligProsjekterendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool erklaeringAnsvarligProsjekterendeSpecified {
            get {
                return this.erklaeringAnsvarligProsjekterendeFieldSpecified;
            }
            set {
                this.erklaeringAnsvarligProsjekterendeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> erklaeringAnsvarligUtfoerende {
            get {
                return this.erklaeringAnsvarligUtfoerendeField;
            }
            set {
                this.erklaeringAnsvarligUtfoerendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool erklaeringAnsvarligUtfoerendeSpecified {
            get {
                return this.erklaeringAnsvarligUtfoerendeFieldSpecified;
            }
            set {
                this.erklaeringAnsvarligUtfoerendeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> erklaeringAnsvarligKontrollerende {
            get {
                return this.erklaeringAnsvarligKontrollerendeField;
            }
            set {
                this.erklaeringAnsvarligKontrollerendeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool erklaeringAnsvarligKontrollerendeSpecified {
            get {
                return this.erklaeringAnsvarligKontrollerendeFieldSpecified;
            }
            set {
                this.erklaeringAnsvarligKontrollerendeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Foretak", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class ForetakType : PartType {
        
        private System.Nullable<bool> harSentralGodkjenningField;
        
        private bool harSentralGodkjenningFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> harSentralGodkjenning {
            get {
                return this.harSentralGodkjenningField;
            }
            set {
                this.harSentralGodkjenningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool harSentralGodkjenningSpecified {
            get {
                return this.harSentralGodkjenningFieldSpecified;
            }
            set {
                this.harSentralGodkjenningFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForetakType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Part", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class PartType {
        
        private KodeType partstypeField;
        
        private string foedselsnummerField;
        
        private KontaktpersonType kontaktpersonField;
        
        private string organisasjonsnummerField;
        
        private string navnField;
        
        private EnkelAdresseType adresseField;
        
        private string telefonnummerField;
        
        private string mobilnummerField;
        
        private string epostField;
        
        private System.Nullable<System.DateTime> signaturdatoField;
        
        private bool signaturdatoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KodeType partstype {
            get {
                return this.partstypeField;
            }
            set {
                this.partstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string foedselsnummer {
            get {
                return this.foedselsnummerField;
            }
            set {
                this.foedselsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KontaktpersonType kontaktperson {
            get {
                return this.kontaktpersonField;
            }
            set {
                this.kontaktpersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string organisasjonsnummer {
            get {
                return this.organisasjonsnummerField;
            }
            set {
                this.organisasjonsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnkelAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobilnummer {
            get {
                return this.mobilnummerField;
            }
            set {
                this.mobilnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> signaturdato {
            get {
                return this.signaturdatoField;
            }
            set {
                this.signaturdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signaturdatoSpecified {
            get {
                return this.signaturdatoFieldSpecified;
            }
            set {
                this.signaturdatoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Kontaktperson", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class KontaktpersonType {
        
        private string navnField;
        
        private string telefonnummerField;
        
        private string mobilnummerField;
        
        private string epostField;
        
        /// <remarks/>
        public string navn {
            get {
                return this.navnField;
            }
            set {
                this.navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefonnummer {
            get {
                return this.telefonnummerField;
            }
            set {
                this.telefonnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mobilnummer {
            get {
                return this.mobilnummerField;
            }
            set {
                this.mobilnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string epost {
            get {
                return this.epostField;
            }
            set {
                this.epostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("EnkelAdresse", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class EnkelAdresseType {
        
        private string adresselinje1Field;
        
        private string adresselinje2Field;
        
        private string adresselinje3Field;
        
        private string postnrField;
        
        private string poststedField;
        
        private string landkodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje1 {
            get {
                return this.adresselinje1Field;
            }
            set {
                this.adresselinje1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje2 {
            get {
                return this.adresselinje2Field;
            }
            set {
                this.adresselinje2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje3 {
            get {
                return this.adresselinje3Field;
            }
            set {
                this.adresselinje3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string landkode {
            get {
                return this.landkodeField;
            }
            set {
                this.landkodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Eiendom", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class EiendomType {
        
        private MatrikkelnummerType eiendomsidentifikasjonField;
        
        private EiendommensAdresseType adresseField;
        
        private string bygningsnummerField;
        
        private string bolignummerField;
        
        private string kommunenavnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MatrikkelnummerType eiendomsidentifikasjon {
            get {
                return this.eiendomsidentifikasjonField;
            }
            set {
                this.eiendomsidentifikasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EiendommensAdresseType adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bygningsnummer {
            get {
                return this.bygningsnummerField;
            }
            set {
                this.bygningsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bolignummer {
            get {
                return this.bolignummerField;
            }
            set {
                this.bolignummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommunenavn {
            get {
                return this.kommunenavnField;
            }
            set {
                this.kommunenavnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelnummer", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class MatrikkelnummerType {
        
        private string kommunenummerField;
        
        private string gaardsnummerField;
        
        private string bruksnummerField;
        
        private string festenummerField;
        
        private string seksjonsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommunenummer {
            get {
                return this.kommunenummerField;
            }
            set {
                this.kommunenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string gaardsnummer {
            get {
                return this.gaardsnummerField;
            }
            set {
                this.gaardsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string bruksnummer {
            get {
                return this.bruksnummerField;
            }
            set {
                this.bruksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string festenummer {
            get {
                return this.festenummerField;
            }
            set {
                this.festenummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string seksjonsnummer {
            get {
                return this.seksjonsnummerField;
            }
            set {
                this.seksjonsnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("EiendommensAdresse", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class EiendommensAdresseType {
        
        private string adresselinje1Field;
        
        private string adresselinje2Field;
        
        private string adresselinje3Field;
        
        private string postnrField;
        
        private string poststedField;
        
        private string landkodeField;
        
        private string gatenavnField;
        
        private string husnrField;
        
        private string bokstavField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje1 {
            get {
                return this.adresselinje1Field;
            }
            set {
                this.adresselinje1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje2 {
            get {
                return this.adresselinje2Field;
            }
            set {
                this.adresselinje2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresselinje3 {
            get {
                return this.adresselinje3Field;
            }
            set {
                this.adresselinje3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postnr {
            get {
                return this.postnrField;
            }
            set {
                this.postnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string poststed {
            get {
                return this.poststedField;
            }
            set {
                this.poststedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string landkode {
            get {
                return this.landkodeField;
            }
            set {
                this.landkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gatenavn {
            get {
                return this.gatenavnField;
            }
            set {
                this.gatenavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string husnr {
            get {
                return this.husnrField;
            }
            set {
                this.husnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bokstav {
            get {
                return this.bokstavField;
            }
            set {
                this.bokstavField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("ErklaeringAnsvarsrett", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class ErklaeringAnsvarsrettType {
        
        private string fraSluttbrukersystemField;
        
        private string hovedinnsendingsnummerField;
        
        private EiendomType[] eiendomByggestedField;
        
        private SaksnummerType kommunensSaksnummerField;
        
        private AnsvarsrettType ansvarsrettField;
        
        private PartType ansvarligSoekerField;
        
        private SignaturType signaturField;
        
        private string prosjektnavnField;
        
        private string prosjektnrField;
        
        private string dataFormatProviderField;
        
        private string dataFormatIdField;
        
        private string dataFormatVersionField;
        
        public ErklaeringAnsvarsrettType() {
            this.dataFormatProviderField = "ANSAKO";
            this.dataFormatIdField = "ErklaeringAnsvarsrett";
            this.dataFormatVersionField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fraSluttbrukersystem {
            get {
                return this.fraSluttbrukersystemField;
            }
            set {
                this.fraSluttbrukersystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hovedinnsendingsnummer {
            get {
                return this.hovedinnsendingsnummerField;
            }
            set {
                this.hovedinnsendingsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("eiendom", IsNullable=false)]
        public EiendomType[] eiendomByggested {
            get {
                return this.eiendomByggestedField;
            }
            set {
                this.eiendomByggestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SaksnummerType kommunensSaksnummer {
            get {
                return this.kommunensSaksnummerField;
            }
            set {
                this.kommunensSaksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AnsvarsrettType ansvarsrett {
            get {
                return this.ansvarsrettField;
            }
            set {
                this.ansvarsrettField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PartType ansvarligSoeker {
            get {
                return this.ansvarligSoekerField;
            }
            set {
                this.ansvarligSoekerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SignaturType signatur {
            get {
                return this.signaturField;
            }
            set {
                this.signaturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prosjektnavn {
            get {
                return this.prosjektnavnField;
            }
            set {
                this.prosjektnavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prosjektnr {
            get {
                return this.prosjektnrField;
            }
            set {
                this.prosjektnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatProvider {
            get {
                return this.dataFormatProviderField;
            }
            set {
                this.dataFormatProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatId {
            get {
                return this.dataFormatIdField;
            }
            set {
                this.dataFormatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatVersion {
            get {
                return this.dataFormatVersionField;
            }
            set {
                this.dataFormatVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Saksnummer", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class SaksnummerType {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Signatur", Namespace="http://skjema.kxml.no/dibk/ansakoAnsvarsrett/v1.0", IsNullable=false)]
    public partial class SignaturType {
        
        private System.DateTime signaturdatoField;
        
        private string signertAvField;
        
        private string signertPaaVegneAvField;
        
        private string signeringsstegField;
        
        /// <remarks/>
        public System.DateTime signaturdato {
            get {
                return this.signaturdatoField;
            }
            set {
                this.signaturdatoField = value;
            }
        }
        
        /// <remarks/>
        public string signertAv {
            get {
                return this.signertAvField;
            }
            set {
                this.signertAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string signertPaaVegneAv {
            get {
                return this.signertPaaVegneAvField;
            }
            set {
                this.signertPaaVegneAvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string signeringssteg {
            get {
                return this.signeringsstegField;
            }
            set {
                this.signeringsstegField = value;
            }
        }
    }
}
